from pathlib import Path
import random


VECTOR_COUNT = 1000
RANDOM_SEED = 0x5A17

PREAMBLE = [
    (1, 0, 10, 2, 3, 4),
    (1, 0, 7, -3, -2, 1),
    (1, 1, -8, 5, 2, -6),
    (0, 0, 0, 0, 0, 0),
    (1, 0, -1, -1, 2, 2),
    (1, 1, 4, 1, 1, -3),
]


def generate_stimulus() -> list[tuple[int, int, int, int, int, int]]:
    rng = random.Random(RANDOM_SEED)
    stimulus = list(PREAMBLE)

    while len(stimulus) < VECTOR_COUNT:
        valid = 0 if rng.randrange(16) == 0 else 1
        last = 1 if (valid and rng.randrange(128) == 0) else 0
        a_re = rng.randint(-32768, 32767)
        a_im = rng.randint(-32768, 32767)
        b_re = rng.randint(-32768, 32767)
        b_im = rng.randint(-32768, 32767)
        stimulus.append((valid, last, a_re, a_im, b_re, b_im))

    valid, _, a_re, a_im, b_re, b_im = stimulus[-1]
    if valid == 0:
        valid = 1
    stimulus[-1] = (valid, 1, a_re, a_im, b_re, b_im)

    return stimulus


def main() -> None:
    stimulus = generate_stimulus()

    if len(stimulus) != VECTOR_COUNT:
        raise SystemExit(f"Expected {VECTOR_COUNT} vectors, got {len(stimulus)}")

    root_dir = Path(__file__).resolve().parents[1]
    output_path = root_dir / "tb" / "input" / "fixed_stage_stim.txt"

    for index, (valid, last, a_re, a_im, b_re, b_im) in enumerate(stimulus, start=1):
        if valid not in (0, 1):
            raise SystemExit(f"Vector {index}: valid must be 0 or 1")
        if last not in (0, 1):
            raise SystemExit(f"Vector {index}: last must be 0 or 1")
        for name, value in (
            ("a_re", a_re),
            ("a_im", a_im),
            ("b_re", b_re),
            ("b_im", b_im),
        ):
            if not (-32768 <= value <= 32767):
                raise SystemExit(f"Vector {index}: {name}={value} is out of int16 range")

    with output_path.open("w", encoding="ascii", newline="\n") as output_file:
        output_file.write("# Generated by scripts/generate_fixed_stage_stim.py\n")
        output_file.write(f"# seed {RANDOM_SEED}\n")
        output_file.write("# valid last a_re a_im b_re b_im\n")
        for valid, last, a_re, a_im, b_re, b_im in stimulus:
            output_file.write(f"{valid} {last} {a_re} {a_im} {b_re} {b_im}\n")

    print(f"Wrote {len(stimulus)} vectors to {output_path}")


if __name__ == "__main__":
    main()
